name: Test cURL for eBay Webhook

on: [push]

jobs:
  test-curl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute cURL Command
      run: |
        curl -X POST https://xiongadget.com/ebay-webhook.php -d '{"verificationToken": "MiTokenDeVerificacion123"}' -H "Content-Type: application/json"
